services:
  # velocity MC powered proxy
  proxy-server:
    image: alohanetworks/proxy
    build:
      context: servers/proxy
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
      - "25565:25565/udp"
    networks:
      - proxy-net
      - default

  # fabric MC Survival server
  survival-server:
    image: alohanetworks/survival
    build:
      context: servers/survival
      dockerfile: Dockerfile
    ports:
      - "25566:25566"
      - "25576:25576" 
      - "24454:24454/udp"
    networks:
      - default 

  # fabric MC Creative server
  creative-server:
    image: alohanetworks/creative
    build:
      context: servers/creative
      dockerfile: Dockerfile
    ports:
      - "25567:25567"
      - "25577:25577"
      - "24455:24455/udp"
    networks:
      - default 

networks:
  proxy-net:
