name = "Aloha Minecraft Network"
proxy = "proxy"
port = 25565

[servers.creative]
port = 25567

[servers.survival]
port = 25566

[variables]
MAX_PLAYERS = "32"
MOTD = "Welcome to the ALOHA Snack Bar Minecraft Network!"

[markdown]
files = ["README.md"]
auto_update = true
