name = "proxy"
mc_version = "3.4.0-SNAPSHOT"

[jar]
type = "velocity"

[variables]
BIND = "0.0.0.0:25565"

[launcher]
nogui = false
eula_args = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[plugins]]
type = "modrinth"
id = "simple-voice-chat"
version = "yGTasgG4"

[[plugins]]
type = "modrinth"
id = "luckperms"
version = "v5.4.145-velocity"

[[plugins]]
type = "ghrel"
repo = "beanbeanjuice/SimpleProxyChat"
tag = "0.5.7"
asset = "SimpleProxyChat-${tag}.jar"
