name = "proxy"
mc_version = "latest"

[jar]
type = "velocity"

[variables]
BIND = "0.0.0.0:25565"

[launcher]
nogui = false
eula_args = true

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[plugins]]
type = "modrinth"
id = "velocitydiscord"
version = "1.9.0"

[[plugins]]
type = "modrinth"
id = "simple-voice-chat"
version = "yGTasgG4"
