name = "creative"
mc_version = "1.21.4"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
VOICE_PORT = "24455"
PORT = "25567"
RCON_PORT = "25577"

[launcher]
eula_args = true
nogui = true
memory = "6G"

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "fabricproxy-lite"
version = "v2.9.0"

[[mods]]
type = "modrinth"
id = "c2me-fabric"
version = "0.3.1.1.0+1.21.4"

[[mods]]
type = "modrinth"
id = "krypton"
version = "0.2.8"

[[mods]]
type = "modrinth"
id = "lithium"
version = "mc1.21.4-0.14.3-fabric"

[[mods]]
type = "modrinth"
id = "worldedit"
version = "7.3.10-beta-01"

[[mods]]
type = "modrinth"
id = "vmp-fabric"
version = "k1tcjmTr"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "IPM0JlHd"

[[mods]]
type = "modrinth"
id = "noisium"
version = "9NHdQfkN"

[[mods]]
type = "modrinth"
id = "recipecooldown"
version = "oe5KEgWu"

[[mods]]
type = "modrinth"
id = "view-distance-fix"
version = "JHg6ZYop"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "gx7PIV8n"

[[mods]]
type = "ghrel"
repo = "gnembon/fabric-carpet"
tag = "1.4.161"
asset = "fabric-carpet-1.21.4-${tag}+v241203.jar"

[[mods]]
type = "ghrel"
repo = "gnembon/carpet-extra"
tag = "1.4.161"
asset = "carpet-extra-1.21.4-${tag}.jar"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "4Zzq92HE"

[[mods]]
type = "modrinth"
id = "audioplayer"
version = "fabric-1.21.4-1.13.2"

[[mods]]
type = "modrinth"
id = "sound-physics-remastered"
version = "fabric-1.21.4-1.4.8"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "8FAH9fuR"

[[mods]]
type = "modrinth"
id = "rei"
version = "18.0.796+fabric"

[[mods]]
type = "modrinth"
id = "architectury-api"
version = "15.0.1+fabric"

[[mods]]
type = "modrinth"
id = "cloth-config"
version = "17.0.144+fabric"
