name = "survival"
mc_version = "1.21.4"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
PORT = "25566"
RCON_PORT = "25576"
VOICE_PORT = "24454"

[launcher]
eula_args = true
nogui = true
memory = "12G"

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "fabricproxy-lite"
version = "AQhF7kvw"

[[mods]]
type = "modrinth"
id = "c2me-fabric"
version = "yGX4O0YU"

[[mods]]
type = "modrinth"
id = "krypton"
version = "Acz3ttTp"

[[mods]]
type = "modrinth"
id = "lithium"
version = "t1FlWYl9"

[[mods]]
type = "modrinth"
id = "terralith"
version = "lQreFvOm"

[[mods]]
type = "modrinth"
id = "spawn-animations"
version = "4q2qDUKg"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "8FAH9fuR"

[[mods]]
type = "modrinth"
id = "nullscape"
version = "dHJAVX8s"

[[mods]]
type = "modrinth"
id = "true-ending"
version = "OegcvXrX"

[[mods]]
type = "modrinth"
id = "vanilla-refresh"
version = "A8QA6lsv"

[[mods]]
type = "modrinth"
id = "hopo-better-underwater-ruins"
version = "j5QsKFXs"

[[mods]]
type = "modrinth"
id = "hopo-better-ruined-portals"
version = "31DRiEea"

[[mods]]
type = "modrinth"
id = "more-mobs"
version = "yZ3Dy1py"

[[mods]]
type = "modrinth"
id = "spellbound-weapons"
version = "AYZsuKK8"

[[mods]]
type = "modrinth"
id = "mastercutter"
version = "VG8PuQZM"

[[mods]]
type = "modrinth"
id = "better-bundle"
version = "8NEGwk3X"

[[mods]]
type = "modrinth"
id = "jakes-build-tools"
version = "AoUxlIEZ"

[[mods]]
type = "modrinth"
id = "reg-more-foods"
version = "3i4n47HR"

[[mods]]
type = "modrinth"
id = "ketkets-furnicraft"
version = "YOUPmqmi"

[[mods]]
type = "modrinth"
id = "colorful-trims"
version = "5oYXZj69"

[[mods]]
type = "modrinth"
id = "gardeners-dream"
version = "Iv48v4cz"

[[mods]]
type = "modrinth"
id = "incendium"
version = "7mVvV9Th"

[[mods]]
type = "modrinth"
id = "appleskin"
version = "cHQjeYVS"

[[mods]]
type = "modrinth"
id = "tectonic"
version = "8uiKNgr3"

[[mods]]
type = "modrinth"
id = "hopo-better-mineshaft"
version = "HBsWqCQW"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns"
version = "PAUVovtf"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-nether-fortress-overhaul"
version = "2RoTZo1S"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-end-castle-standalone"
version = "swvo49Be"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-pillager-outpost-overhaul"
version = "4TcaQ5bc"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-woodland-mansion-replacement"
version = "rIKtpRlB"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-swamp-hut-overhaul"
version = "X7Zkca4c"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-stronghold-overhaul"
version = "eZabSTZt"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-ocean-monument-replacement"
version = "itCK7YcZ"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-desert-temple-replacement"
version = "4dZzlZdy"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-jungle-temple-replacement"
version = "Lmk8Cscm"

[[mods]]
type = "modrinth"
id = "dungeons-and-taverns-ancient-city-overhaul"
version = "hwJRJI7p"

[[mods]]
type = "modrinth"
id = "vmp-fabric"
version = "k1tcjmTr"

[[mods]]
type = "modrinth"
id = "ferrite-core"
version = "IPM0JlHd"

[[mods]]
type = "modrinth"
id = "noisium"
version = "9NHdQfkN"

[[mods]]
type = "modrinth"
id = "recipecooldown"
version = "oe5KEgWu"

[[mods]]
type = "modrinth"
id = "view-distance-fix"
version = "JHg6ZYop"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "gx7PIV8n"

[[mods]]
type = "ghrel"
repo = "gnembon/fabric-carpet"
tag = "1.4.161"
asset = "fabric-carpet-1.21.4-${tag}+v241203.jar"

[[mods]]
type = "ghrel"
repo = "gnembon/carpet-extra"
tag = "1.4.161"
asset = "carpet-extra-1.21.4-${tag}.jar"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "4Zzq92HE"

[[mods]]
type = "modrinth"
id = "audioplayer"
version = "fabric-1.21.4-1.13.2"

[[mods]]
type = "modrinth"
id = "sound-physics-remastered"
version = "fabric-1.21.4-1.4.8"

[[mods]]
type = "modrinth"
id = "rei"
version = "18.0.796+fabric"

[[mods]]
type = "modrinth"
id = "architectury-api"
version = "15.0.1+fabric"

[[mods]]
type = "modrinth"
id = "cloth-config"
version = "17.0.144+fabric"

[[mods]]
type = "modrinth"
id = "lmd"
version = "e0AXgTFp"

[[mods]]
type = "modrinth"
id = "chunky"
version = "VkAgASL1"

[[mods]]
type = "modrinth"
id = "almanac"
version = "inGMPti6"
